### ISSUE TITLE
What is wrong with rs/zerolog?

### ISSUE THREAD

**Issue by frederikhors** [echocat/slf4g#1]
What is wrong with https://github.com/rs/zerolog?

No offense. Just to better understand your opinion.

**Comment by blaubaer** [comment]
Sorry for the late response,

[`slf4g`](https://github.com/echocat/slf4g) is a logger made for adjust to your needs and integrate with many other existing frameworks. For example for:
1. [`logrus`](https://github.com/sirupsen/logrus) (using [`slf4g-logrus`](https://github.com/echocat/slf4g-logrus))
2. [`klog`](https://github.com/kubernetes/klog) (using [`slf4g-klog`](https://github.com/echocat/slf4g-klog))
3. [`logr`](https://github.com/go-logr/logr) (using [`slf4g-logr`](https://github.com/echocat/slf4g-logr))
4. Or obviously also the default Go logger using the [`sdk/bridge`](https://github.com/echocat/slf4g/tree/main/sdk/bridge)

...often you're using libraries which does simply *not like* your logging library. In those cases you often ending up in different log outputs. This logger library is made in way to make it easier to adapt to those (if not already - as listed above - integrations are available).

On top of that you can customize as you want. JSON (obviously), Text (color and plain) and your own stuff.

Structures of logger: ROOT->A->B->C ... and so on...

In general, I hoped I was able to explain it in the [motivation section](https://github.com/echocat/slf4g#motivation).

Cheers
